### ISSUE TITLE
[🐛 Bug]: Selenium Manager - Exec format error

### ISSUE THREAD

**Issue by bananensplit** [SeleniumHQ/seleniumhq.github.io#1481]
### What happened?

Hey!

I recently ran into something I think is a bug. I was recently working on a docker deployment for one of my projects and ran into the following issue. I tried running Selenium in a docker container but couldn't get it to work because every time I executed my python script an exception was thrown.

I recreated a minimal example below.

### Reproduce
This is a minimal reproduction of the bug that I encountered. Run the following commands in order and you should see the error message below.

```bash
# Create a dockercontainer
docker run -dt --rm --name python-box python:3.11-bookworm

# Enter the container bash
docker exec -it python-box bash

# In the container bash run the following
cd /usr/src/
apt update
apt install firefox-esr
pip install selenium
echo "from selenium import webdriver
driver = webdriver.Firefox()" > main.py

# Run the script
export DISPLAY=:20
python main.py
```

Error message:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 126, in run
    completed_proc = subprocess.run(args, capture_output=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 95, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 132, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/main.py", line 3, in <module>
    driver = webdriver.Firefox()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### What I think happens
The first error states that `selenium-manager` is not in the correct exec format. This usually means that the exec file is not compiled for the architecture the system is currently running (in my case `aarch64`).

Therefore the manager can not be executed and can not fulfill it's duty as a driver-manager.

### What browsers and operating systems are you seeing the problem on?

Sepcs:
- OS: Ubuntu 22.04.1 LTS (jammy)
- Architecture: aarch64 (this will be important)
- Docker version 20.10.17
- Selenium version 4.12.0
- Firefox version 102.15.1esr

**Comment by bananensplit** [comment]
I noticed that this is the wrong place to discuss this kind of issues!
I am closing this issue and reopening it in the under https://github.com/SeleniumHQ/selenium/issues
Sorry!
