### ISSUE TITLE
Unable to find WebDriverError@chrome://marionette/content/error.js to read failed line

### ISSUE THREAD

**Issue by thebravoman** [SeleniumHQ/seleniumhq.github.io#509]
## 🐛 Bug Report
This started occurring in all specs
```
  187.3) Failure/Error: Unable to find WebDriverError@chrome://marionette/content/error.js to read failed line

              Selenium::WebDriver::Error::InvalidArgumentError:
                Expected "handle" to be a string, got [object Undefined] undefined



              # WebDriverError@chrome://marionette/content/error.js:175:5
              # InvalidArgumentError@chrome://marionette/content/error.js:304:5
              # assert.that/<@chrome://marionette/content/assert.js:479:13
              # assert.string@chrome://marionette/content/assert.js:383:53
              # GeckoDriver.prototype.switchToWindow@chrome://marionette/content/driver.js:1645:10
              # despatch@chrome://marionette/content/server.js:305:40
              # execute@chrome://marionette/content/server.js:275:16
              # onPacket/<@chrome://marionette/content/server.js:248:20
              # onPacket@chrome://marionette/content/server.js:249:9
              # _onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:136:in `switch_to_window'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/target_locator.rb:80:in `window'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:222:in `switch_to_window'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara/selenium/driver_specializations/firefox_driver.rb:54:in `reset!'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara/session.rb:130:in `reset!'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara.rb:325:in `block in reset_sessions!'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara.rb:325:in `reverse_each'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara.rb:325:in `reset_sessions!'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/capybara-3.33.0/lib/capybara/rspec.rb:18:in `block (2 levels) in <top (required)>'
              # /usr/local/rvm/gems/ruby-2.6.5/gems/rspec-prof-0.0.7/lib/rspec-prof.rb:76:in `block (2 levels) in <top (required)>'
```

We are running rails specs with selenium driver. 

## To Reproduce
It just started occurring on our side. We are trying to come up with a way to reproduce it. 

## Expected behavior
I would expect the tests to pass.

## Environment

* OS: Ubuntu 18.04.4 LTS
* Browser: Chrome
chromedriver --version
ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882})

**Comment by harsha509** [comment]
Hi @thebravoman ,

This section contains issues related to Selenium documentation only. Can you please raise it in here https://github.com/SeleniumHQ/selenium/issues

Also, request you please provide a SSCCE (http://sscce.org/) to reproduce the issue.

Thanks,
Harsha

**Comment by thebravoman** [comment]
Thanks. Switched to chrome. Will do for now.
